audit_header: false
title: Washington DC Real Estate Video Blog with Allen Johnson
description: >-
  Our mission at AJ Team Realty is to be your best resource for Washington DC
  real estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The AJ Team Realty, your professional
  Washington DC Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: true
custom_links_new_tab:
  - title: FREE Audiobook
    url: https://whatyouragentwonttellyou.paperform.co/
client:
  name: Allen Johnson
  title:
  license_number:
  about_markdown: >-
    AJ Team Realty is comprised of a team of local real estate professionals
    committed to selling some of the most desired homes in the Washington DC
    Metro Area. Selling these "right addresses" is the mission of AJ Team
    Realty. Let us know what you're looking for.
  brand: AJ Team Realty
  brokerage: Keller Williams
  market: Washington DC
  address: 4310 Prince William Pkwy Ste 200 Woodbridge, VA 22192
  phone: 703-991-7900
  phone_type:
  phone2:
  phone2_type:
  email: connect@AJTeamRealty.com
  url: http://AJTeamRealty.com
forms:
  sitekey: 6LdDHNAaAAAAACPDqaABlYJMqT9NIn0JbFiKZz4i
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.ajteamrealty.com/home-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: >-
    https://www.ajteamrealty.com/results-gallery/?photo=1&sort=importdate&status=A%2CCS
  third_CTA_text: Search Foreclosures
  third_CTA_URL: >-
    https://www.ajteamrealty.com/results-gallery/?county=36041%2C36067%2C36081%2C36079%2C36118%2C36085%2C36045&featureor=BO%2CSS&sort=importdate&status=A
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: What’s Your Washington DC Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: https://www.ajteamrealty.com/home-valuation/
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a Washington DC Home?
    CTA_text2: Search the entire MLS for your Washington DC home.
    CTA_link_text2: Search the MLS
    CTA_url2: >-
      https://www.ajteamrealty.com/results-gallery/?photo=1&sort=importdate&status=A%2CCS
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/ajteamrealty/
  linkedin_url: https://www.linkedin.com/in/ajteamrealty/
  youtube_url: https://www.youtube.com/c/AJTeamRealty?sub_confirmation=1
  twitter_url: https://twitter.com/ajteamrealty
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Washington DC Real Estate Podcast with Allen Johnson
  categories: Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Washington
    DC Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from AJ Team Realty - your professional
    Washington DC Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Washington DC,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Allen Johnson
images:
  client_headshot_path: /uploads/3headshot.png
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Washington DC Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#b40101'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: rgba(0, 0, 0, 0)
  secondary_button_text_color: '#ffffff'
